title: depo of random bits
description: meh programmer's mindspace
author:
  name: "Zank613"
  email: "nomail@.com"
theme: minima

# Optional extras
markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-seo-tag

minima:
  social_links:
    - title: GitHub
      icon: github
      url: "https://github.com/Zank613?tab=repositories"

  skin: dark

  show_excerpts: true

  # Optional: Custom nav items
  navigation:
    - title: "Home"
      url: "/"
    - title: "Blog"
      url: "/blog.html"
    - title: "Projects"
      url: "/projects.html"