title: zank613 mind-depo
description: a meh programmer's mindspace
author:
  name: Zank613
  email: nomail@.com
theme: minima

# Optional extras
markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-seo-tag

minima:
  skin: dark
  show_excerpts: true

  social_links:
    github: Zank613

  navigation:
    - title: "Home"
      url: "/"
    - title: "Blog"
      url: "/blog.html"
    - title: "Projects"
      url: "/projects.html"


collections:
  projects:
    output: true